# docker-compose.yml

version: '3.8'

volumes:
  # Config Server Data Volumes
  configsvr01_data: {}
  configsvr02_data: {}
  configsvr03_data: {}

  # Shard 1 Data Volumes
  shard01a_data: {}
  # shard01b_data: {} # 주석 해제하여 샤드1 레플리카 멤버 추가 가능
  # shard01c_data: {} # 주석 해제하여 샤드1 레플리카 멤버 추가 가능

  # Shard 2 Data Volumes
  shard02a_data: {}
  # shard02b_data: {} # 주석 해제하여 샤드2 레플리카 멤버 추가 가능
  # shard02c_data: {} # 주석 해제하여 샤드2 레플리카 멤버 추가 가능

networks:
  mongo-cluster:
    driver: bridge

services:
  # --- Configuration Servers (Replica Set: csrs) ---
  configsvr01:
    image: mongo:latest
    container_name: configsvr01
    command: mongod --configsvr --replSet csrs --port 27017 --bind_ip_all
    volumes:
      - configsvr01_data:/data/configdb
    networks:
      - mongo-cluster
    restart: always

  configsvr02:
    image: mongo:latest
    container_name: configsvr02
    command: mongod --configsvr --replSet csrs --port 27017 --bind_ip_all
    volumes:
      - configsvr02_data:/data/configdb
    networks:
      - mongo-cluster
    restart: always

  configsvr03:
    image: mongo:latest
    container_name: configsvr03
    command: mongod --configsvr --replSet csrs --port 27017 --bind_ip_all
    volumes:
      - configsvr03_data:/data/configdb
    networks:
      - mongo-cluster
    restart: always

  # --- Shard 1 Servers (Replica Set: shard01rs) ---
  shard01a:
    image: mongo:latest
    container_name: shard01a
    command: mongod --shardsvr --replSet shard01rs --port 27017 --bind_ip_all
    volumes:
      - shard01a_data:/data/db
    networks:
      - mongo-cluster
    restart: always

  # --- Shard 2 Servers (Replica Set: shard02rs) ---
  shard02a:
    image: mongo:latest
    container_name: shard02a
    command: mongod --shardsvr --replSet shard02rs --port 27017 --bind_ip_all
    volumes:
      - shard02a_data:/data/db
    networks:
      - mongo-cluster
    restart: always

  # --- Mongos Router ---
  mongos01:
    image: mongo:latest
    container_name: mongos01
    command: >
      mongos --configdb csrs/configsvr01:27017,configsvr02:27017,configsvr03:27017
      --port 27017
      --bind_ip_all
    ports:
      - "27017:27017" # 외부 접속을 위해 호스트 포트와 연결
    networks:
      - mongo-cluster
    depends_on:
      - configsvr01
      - configsvr02
      - configsvr03
      - shard01a
      - shard02a
    restart: always
    # healthcheck 추가하여 mongos가 config server 준비될 때까지 기다리도록 설정 가능 (복잡도 증가)