# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.proto import product_pb2 as src_dot_proto_dot_product__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in src/proto/product_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProductServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateProduct = channel.unary_unary(
                '/product.ProductService/CreateProduct',
                request_serializer=src_dot_proto_dot_product__pb2.CreateProductRequest.SerializeToString,
                response_deserializer=src_dot_proto_dot_product__pb2.ProductResponse.FromString,
                _registered_method=True)
        self.CreateProductsBulk = channel.unary_unary(
                '/product.ProductService/CreateProductsBulk',
                request_serializer=src_dot_proto_dot_product__pb2.CreateProductBulkRequest.SerializeToString,
                response_deserializer=src_dot_proto_dot_product__pb2.ProductResponse.FromString,
                _registered_method=True)
        self.UpdateProduct = channel.unary_unary(
                '/product.ProductService/UpdateProduct',
                request_serializer=src_dot_proto_dot_product__pb2.UpdateProductRequest.SerializeToString,
                response_deserializer=src_dot_proto_dot_product__pb2.ProductResponse.FromString,
                _registered_method=True)
        self.UpdateProductsBulk = channel.unary_unary(
                '/product.ProductService/UpdateProductsBulk',
                request_serializer=src_dot_proto_dot_product__pb2.UpdateProductBulkRequest.SerializeToString,
                response_deserializer=src_dot_proto_dot_product__pb2.ProductResponse.FromString,
                _registered_method=True)
        self.DeleteProduct = channel.unary_unary(
                '/product.ProductService/DeleteProduct',
                request_serializer=src_dot_proto_dot_product__pb2.DeleteProductRequest.SerializeToString,
                response_deserializer=src_dot_proto_dot_product__pb2.ProductResponse.FromString,
                _registered_method=True)
        self.DeleteProductsBulk = channel.unary_unary(
                '/product.ProductService/DeleteProductsBulk',
                request_serializer=src_dot_proto_dot_product__pb2.DeleteProductBulkRequest.SerializeToString,
                response_deserializer=src_dot_proto_dot_product__pb2.ProductResponse.FromString,
                _registered_method=True)
        self.SendProcessedProduct = channel.unary_unary(
                '/product.ProductService/SendProcessedProduct',
                request_serializer=src_dot_proto_dot_product__pb2.ProcessedProductRequest.SerializeToString,
                response_deserializer=src_dot_proto_dot_product__pb2.ProcessedProductResponse.FromString,
                _registered_method=True)
        self.ResendProcessedProduct = channel.unary_unary(
                '/product.ProductService/ResendProcessedProduct',
                request_serializer=src_dot_proto_dot_product__pb2.ProcessedProductRequest.SerializeToString,
                response_deserializer=src_dot_proto_dot_product__pb2.ProcessedProductResponse.FromString,
                _registered_method=True)


class ProductServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateProduct(self, request, context):
        """PIM -> PMP
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateProductsBulk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProductsBulk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteProductsBulk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendProcessedProduct(self, request, context):
        """PMP -> POC 로 처리된 상품 정보 전송
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResendProcessedProduct(self, request, context):
        """POC -> PIM 전달 받은 상품 정보 재전송
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProductServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProduct,
                    request_deserializer=src_dot_proto_dot_product__pb2.CreateProductRequest.FromString,
                    response_serializer=src_dot_proto_dot_product__pb2.ProductResponse.SerializeToString,
            ),
            'CreateProductsBulk': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProductsBulk,
                    request_deserializer=src_dot_proto_dot_product__pb2.CreateProductBulkRequest.FromString,
                    response_serializer=src_dot_proto_dot_product__pb2.ProductResponse.SerializeToString,
            ),
            'UpdateProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProduct,
                    request_deserializer=src_dot_proto_dot_product__pb2.UpdateProductRequest.FromString,
                    response_serializer=src_dot_proto_dot_product__pb2.ProductResponse.SerializeToString,
            ),
            'UpdateProductsBulk': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProductsBulk,
                    request_deserializer=src_dot_proto_dot_product__pb2.UpdateProductBulkRequest.FromString,
                    response_serializer=src_dot_proto_dot_product__pb2.ProductResponse.SerializeToString,
            ),
            'DeleteProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteProduct,
                    request_deserializer=src_dot_proto_dot_product__pb2.DeleteProductRequest.FromString,
                    response_serializer=src_dot_proto_dot_product__pb2.ProductResponse.SerializeToString,
            ),
            'DeleteProductsBulk': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteProductsBulk,
                    request_deserializer=src_dot_proto_dot_product__pb2.DeleteProductBulkRequest.FromString,
                    response_serializer=src_dot_proto_dot_product__pb2.ProductResponse.SerializeToString,
            ),
            'SendProcessedProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.SendProcessedProduct,
                    request_deserializer=src_dot_proto_dot_product__pb2.ProcessedProductRequest.FromString,
                    response_serializer=src_dot_proto_dot_product__pb2.ProcessedProductResponse.SerializeToString,
            ),
            'ResendProcessedProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.ResendProcessedProduct,
                    request_deserializer=src_dot_proto_dot_product__pb2.ProcessedProductRequest.FromString,
                    response_serializer=src_dot_proto_dot_product__pb2.ProcessedProductResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'product.ProductService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('product.ProductService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProductService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.ProductService/CreateProduct',
            src_dot_proto_dot_product__pb2.CreateProductRequest.SerializeToString,
            src_dot_proto_dot_product__pb2.ProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateProductsBulk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.ProductService/CreateProductsBulk',
            src_dot_proto_dot_product__pb2.CreateProductBulkRequest.SerializeToString,
            src_dot_proto_dot_product__pb2.ProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.ProductService/UpdateProduct',
            src_dot_proto_dot_product__pb2.UpdateProductRequest.SerializeToString,
            src_dot_proto_dot_product__pb2.ProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateProductsBulk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.ProductService/UpdateProductsBulk',
            src_dot_proto_dot_product__pb2.UpdateProductBulkRequest.SerializeToString,
            src_dot_proto_dot_product__pb2.ProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.ProductService/DeleteProduct',
            src_dot_proto_dot_product__pb2.DeleteProductRequest.SerializeToString,
            src_dot_proto_dot_product__pb2.ProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteProductsBulk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.ProductService/DeleteProductsBulk',
            src_dot_proto_dot_product__pb2.DeleteProductBulkRequest.SerializeToString,
            src_dot_proto_dot_product__pb2.ProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendProcessedProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.ProductService/SendProcessedProduct',
            src_dot_proto_dot_product__pb2.ProcessedProductRequest.SerializeToString,
            src_dot_proto_dot_product__pb2.ProcessedProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResendProcessedProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.ProductService/ResendProcessedProduct',
            src_dot_proto_dot_product__pb2.ProcessedProductRequest.SerializeToString,
            src_dot_proto_dot_product__pb2.ProcessedProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
